# Generated by Django 4.2.1 on 2023-05-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.DateTimeField()),
                ('type', models.CharField(max_length=100)),
                ('volume', models.FloatField()),
                ('symbol', models.CharField(max_length=100)),
                ('opening_price', models.FloatField()),
                ('volumn_spent', models.FloatField()),
                ('closing_time', models.DateTimeField()),
                ('price', models.FloatField()),
                ('profit', models.FloatField()),
            ],
        ),
    ]
