# Generated by Django 4.2.1 on 2023-06-07 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.DateTimeField()),
                ('type', models.CharField(max_length=100)),
                ('volume', models.FloatField(null=True)),
                ('symbol', models.CharField(max_length=100, null=True)),
                ('opening_price', models.FloatField(null=True)),
                ('volumn_spent', models.FloatField(null=True)),
                ('closing_time', models.DateTimeField(null=True)),
                ('price', models.FloatField(null=True)),
                ('profit', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usermodel')),
            ],
            options={
                'ordering': ('-opening_time',),
            },
        ),
    ]
