# Generated by Django 4.2.1 on 2023-06-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='closing_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='commision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='net_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='opening_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='swap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='symbol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='volume_spent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
