# Generated by Django 4.2.1 on 2023-05-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_datamodel_closing_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='opening_time',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
