# Generated by Django 4.2.1 on 2023-05-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_datamodel_id_alter_datamodel_opening_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datamodel',
            options={'ordering': ('-opening_time',)},
        ),
    ]
