# Generated by Django 4.2.1 on 2023-05-25 12:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_datamodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='closing_time',
            field=core.models.CompositeDateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='opening_time',
            field=core.models.CompositeDateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='profit',
            field=core.models.CompositeFloatField(null=True),
        ),
        migrations.AddConstraint(
            model_name='datamodel',
            constraint=models.UniqueConstraint(fields=('opening_time', 'profit'), name='composite_pk'),
        ),
    ]
